config/routes.rb
Rails.application.routes.draw do
  resources :urls, only: [:index, :new, :create]
  root 'urls#new'
  get 'my', to: 'urls#my'
  resources :reports, only: [:index]
  get 'per_day', to: 'reports#per_day'
  post 'per_day', to: 'reports#per_day'
  get ':short_url', to: 'urls#redirect'
end

app/models/url.rb
require 'securerandom'

class Url < ActiveRecord::Base
  validates :full_url, :url => true
  scope :user_urls, -> (authentication_token){ where(authentication_token: authentication_token) }
  scope :date, -> (created_at){ where(created_at: created_at..created_at+1) }
  def self.create_url(full_url, authentication_token)
    url = Url.new
    url.active = true
    url.full_url = full_url
    url.authentication_token = authentication_token
    url.short_url = SecureRandom.urlsafe_base64(7)
    url.valid? ? ensure_save(url) : url
  end

  def self.ensure_save(url)
    url.save!
    url
  rescue ActiveRecord::RecordNotUnique
    url.short_url = SecureRandom.urlsafe_base64(7)
    ensure_save(url)
  end
end

app/controllers/application_controller.rb
require "digest/md5"
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception
  before_filter :check_authorisation, :update_daily_summary

  def check_authorisation
    session[:authentication_token] ||= Digest::MD5.hexdigest(Time.now.to_s).to_s
  end
  def update_daily_summary
    session[:count] = Url.user_urls(session[:authentication_token]).date(Date.current).all.count
    session[:price] = PriceCalculator.new.calculate_price(session[:count])
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    all_urls_by_user = Url.user_urls(session[:authentication_token]).all
    @result = PriceCalculator.new.calculation_result(all_urls_by_user)
  end

  def per_day
    if params[:date]
      @date = params[:date].to_date
      all_urls_per_day = Url.user_urls(session[:authentication_token]).date(@date).all
      @result = PriceCalculator.new.calculation_result(all_urls_per_day)[0]
    end
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  def index
    @urls = Url.all
  end

  def my
    @urls = Url.user_urls(session[:authentication_token]).all
  end

  def redirect
    @url = Url.where(short_url: params[:short_url], active: true).first
    if @url
      @url.active = false
      @url.save
      redirect_to @url.full_url
    else
      redirect_to urls_path, error: t(:url_not_found)
    end
  end

  def new
    @url = Url.new
  end

  def create
    @url = Url.create_url(url_params[:full_url], session[:authentication_token])
    respond_to do |format|
      if @url.valid?
        format.html { redirect_to my_path, notice: t(:url_create) }
        format.json { render :index, status: :created, location: urls_path }
      else
        format.html { render :new }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end

  end

  private
  def url_params
    params.require(:url).permit(:full_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>URL shortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag  "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">URL Shortener</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= t(:listing_urls) %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to t(:all_listing_urls), urls_path %></li>
                <li><%= link_to t(:my_listing_urls), my_path %></li>
              </ul>
            </li>
            <li><%= link_to t(:new_url), new_url_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= t(:reports) %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to t(:report_all_days), reports_path %></li>
                <li><%= link_to t(:report_per_day), per_day_path %></li>
              </ul>
            </li>
          </ul>
          <p class="navbar-text navbar-right">
            <%= t(:urls_count) %> 
            <%= session[:count]  %>
            <%= t(:price) %>
            <%= number_to_currency(session[:price], unit: "$", format: "%u %n") %>
          </p>
        </div>
      </div>
    </nav>
    <p id="notice"> <span class="label label-warning"><%= notice %></span></p>
    <%= yield %>
  </div>
</body>
</html>

app/views/reports/index.html.erb
<h1><%= t(:reports)%>: <%= t(:report_all_days)%></h1>
<% if @result.present? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t(:date) %></th>
        <th><%= t(:urls_count) %></th>
        <th><%= t(:price) %></th>
      </tr>
    </thead>
    <tbody>
    <% @result.each do |row| %>
      <tr>
        <td><%= row[:date] %></td>
        <td><%= row[:count] %></td>
        <td><%= number_to_currency(row[:price], unit: "$", format: "%u %n") %></td>
      </tr>
    <% end %>    
    </tbody>
  </table>
<% else %>
  <%= t(:no_added_urls) %>
<% end %>

app/views/reports/per_day.html.erb
<h1><%= t(:reports)%>: <%= t(:report_per_day)%></h1>
<%= form_tag('/per_day') do |f| %>
  <input data-provide="datepicker" name="date" data-date-format="dd/mm/yyyy">
  <%= submit_tag t(:report) %>
<% end %>
<p><%= t(:per_day_info) %></p>
<% if @result.present? %>
  <%= t(:date) %>
  <%= @result[:date] %><br>
  <%= t(:urls_count) %>
  <%= @result[:count] %><br>
  <%= t(:price) %>
  <%= number_to_currency(@result[:price], unit: "$", format: "%u %n") %><br>
<% else %>
  <% if @date %>
    <%= t(:no_urls_per_day, date: @date) %>
  <% end %>
<% end %>
<br><br><br><br><br><br><br><br><br><br>

app/views/urls/_form.html.erb
<%= form_for(@url) do |f| %>
  <% if @url.errors.any? %>
    <div class="row">
      <div class="col-md-12">
        <% @url.errors.full_messages.each do |message| %>
          <span class="label label-danger">
            <%= message %>
          </span>
          <br>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-12">
      <%= t(:input_url) %><br>
      <%= f.text_field :full_url, :style => "width: 600px", placeholder: "http://centrmebliv.com.ua/stoly-ta-stiltsi/stoly-zi-sklyanoyu-poverhneyu/Page-6-20" %>
      <%= f.submit t(:shorten) %>
    </div>
  </div>
<% end %>

app/views/urls/_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t(:Added_at)%></th>
      <th><%= t(:full_url)%></th>
      <th><%= t(:short_url)%></th>
      <th><%= t(:active)%></th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <% if url.active %>
      <tr>
      <% else %>
      <tr style="text-decoration:line-through">
      <% end %>
        <td>
          <%= url.created_at.to_date %>
        </td>
        <td><%= url.full_url %></td>
        <% if url.active %>
          <td><%= link_to url.short_url, url.short_url %></td>
        <% else %>
          <td><%= url.short_url %></td>
        <% end %>
        <td><%= url.active %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/urls/index.html.erb
<h1><%= t(:all_listing_urls)%></h1>
<% if @urls.present? %>
  <%= render 'list' %>
<% else %>
  <%= t(:no_added_urls_for_all) %>
<% end %>

app/views/urls/my.html.erb
<h1><%= t(:my_listing_urls)%></h1>
<% if @urls.present? %>
  <%= render 'list' %>
<% else %>
  <%= t(:no_added_urls) %>
<% end %>

app/views/urls/new.html.erb
<%= render 'form' %>